### ISSUE TITLE
Path Format Configuration not working on multi-disc albums

### ISSUE THREAD

**Issue by Victorbry99** [HOZHENWAI/Beets-Plugin_VGMdb#15]
path format configuration is not respected on multi-disc albums, but it works on single-disc albums. I tried 2 configurations for managing multi-disc albums, both working with musicbrainz:
```
paths:
    default: $album%aunique{}/$disc-$track $title
```

```
plugins: inline
paths:
    default: $album%aunique{}/%if{$multidisc,Disc $disc/}$track $title
item_fields:
    multidisc: 1 if disctotal > 1 else 0
```
the plugin ignores them and always places multi-disc albums in a folder under another one, called 'Compilations', with all the tracks mixed together, regardeless of  my config.

here is example album for debugging:
https://vgmdb.net/album/27021
https://musicbrainz.org/release/3cf7f8ef-239f-47db-8537-3882ce65a750
